### PR TITLE
nudge components also on 'incoming' event, which is done by re-run push

### PR DESCRIPTION
**Pull request by rcerven**
pipeline

### Checklist:
 - PR has reference to the issue(s) it resolves
 - Write / update unit tests
 - Write / update integration (envtest) tests
 - Ensure there is an issue for e2e tests if needed
 - Ensure `make test` passes
 - Ensure test coverage hasn't decreased
 - Test code changes manually
 - Update readme and documentation
 - Write PR description that highlights overall changes and add usage examples if applicable

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
Are `incoming` pipelines always push pipelines?

**Comment by rcerven** [comment]
> Are `incoming` pipelines always push pipelines?

yes

**Review by mmorhun — APPROVED** [review]

**Comment by chmeliik** [comment]
> > Are `incoming` pipelines always push pipelines?
> 
> yes

Could you expand? That's not generally true, is it? Is it only true with the Red Hat Konflux UI? Is it a limitation of build-service? A limitation of PaC?

**Comment by rcerven** [comment]
> > > Are `incoming` pipelines always push pipelines?
> > 
> > 
> > yes
> 
> Could you expand? That's not generally true, is it? Is it only true with the Red Hat Konflux UI? Is it a limitation of build-service? A limitation of PaC?

build service is basically re-running explicitly COMPONENT-on-push pipeline
'-on-push' is hardcoded

generally PaC allows to re-run anything but we are explicitly specifying the pipeline :)

**Review by chmeliik — APPROVED** [review]

**Pull request merged**
