### PR TITLE
Move repo to konflux-ci org

### PR DESCRIPTION
**Pull request by chmeliik**
[STONEBLD-2336](https://issues.redhat.com//browse/STONEBLD-2336)

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

### CODE REVIEW

**Comment by chmeliik** [comment]
Should be merged soon after https://github.com/redhat-appstudio/infra-deployments/pull/3658, but not before (because of the changes in `.tekton/push.yaml`)

**Comment by chmeliik** [comment]
> /retest

Oh yeah, this probably won't work because PaC is currently not watching this repo. https://github.com/redhat-appstudio/infra-deployments/pull/3658 needs to be merged first (it updates the url in the PaC Repository object).

**Review by rcerven — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Pull request merged**
