### PR TITLE
when url to github doesn't have all parts it shouldn't crash controller

### PR DESCRIPTION
**Pull request by rcerven**
with index out of range

example url https://github.com/owner

### Checklist:
 - PR has reference to the issue(s) it resolves
 - Write / update unit tests
 - Write / update integration (envtest) tests
 - Ensure there is an issue for e2e tests if needed
 - Ensure `make test` passes
 - Ensure test coverage hasn't decreased
 - Test code changes manually
 - Update readme and documentation
 - Write PR description that highlights overall changes and add usage examples if applicable

### CODE REVIEW

**Review by lcarva — APPROVED** [review]
It would be good to have a unit test to prevent this from accidentally happening again :wink:

**Review by tkdchen — COMMENTED** [review]
It's always easy-to-read-and-understand by using `net/url` to parse the URL.

Also, please add unit tests.

**Review by mmorhun — APPROVED** [review]

**Review by tkdchen — APPROVED** [review]

**Pull request merged**
